name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Firebase secrets into config
        run: |
          cp firebase-config.template.js firebase-config.js
          sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" firebase-config.js
          sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" firebase-config.js
          sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/g" firebase-config.js
          sed -i "s/FIREBASE_STORAGE_BUCKET_PLACEHOLDER/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" firebase-config.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" firebase-config.js
          sed -i "s/FIREBASE_APP_ID_PLACEHOLDER/${{ secrets.FIREBASE_APP_ID }}/g" firebase-config.js

      - name: Inject TinyMCE key into HTML
        run: |
          sed -i "s/TINYMCE_API_KEY_PLACEHOLDER/${{ secrets.TINYMCE_API_KEY }}/g" admin/index.html
      
      - name: Remove template file
        run: rm firebase-config.template.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: .
          clean: true
          force: true
          respect-gitignore: false